config/routes.rb
KdsTalks::Application.routes.draw do
  root to: 'home#index'

  resources :talks

  mount HelloEngine::Engine => '/hello'
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :href, :speaker, :title

  has_many :watches
  has_many :watchers, through: :watches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
    @talks = Talk.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_topnav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Home', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="divider"></li>
      <li><%= link_to 'Talks', talks_path %></li>
    </ul>

    <ul class="right">
      <li class="divider"></li>
      <%# TODO login link here? %>
    </ul>
  </section>
</nav>

app/views/home/index.html.erb
<h1>KDS Talks</h1>
<p>
  Welcome.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>KDS Talks</title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'application/topnav' %>

    <% if notice or alert %>
      <div class="row">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <div class="row">
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/talks/index.html.erb
<h1>Talks</h1>

<ul>
  <% for talk in @talks %>
    <li>
      <strong><%= link_to talk.title, talk.href, class: 'reveal' %></strong>
      <small>By <%= talk.speaker %></small><br />
    </li>
  <% end %>
</ul>